/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { IDL } from '@icp-sdk/core/candid';

export const ClothingItem = IDL.Record({
  'id' : IDL.Nat,
  'name' : IDL.Text,
  'imageUrl' : IDL.Text,
  'category' : IDL.Text,
});

export const idlService = IDL.Service({
  'getAllItems' : IDL.Func([], [IDL.Vec(ClothingItem)], ['query']),
  'getItemById' : IDL.Func([IDL.Nat], [ClothingItem], ['query']),
  'getItemsByCategory' : IDL.Func(
      [IDL.Text],
      [IDL.Vec(ClothingItem)],
      ['query'],
    ),
});

export const idlInitArgs = [];

export const idlFactory = ({ IDL }) => {
  const ClothingItem = IDL.Record({
    'id' : IDL.Nat,
    'name' : IDL.Text,
    'imageUrl' : IDL.Text,
    'category' : IDL.Text,
  });
  
  return IDL.Service({
    'getAllItems' : IDL.Func([], [IDL.Vec(ClothingItem)], ['query']),
    'getItemById' : IDL.Func([IDL.Nat], [ClothingItem], ['query']),
    'getItemsByCategory' : IDL.Func(
        [IDL.Text],
        [IDL.Vec(ClothingItem)],
        ['query'],
      ),
  });
};

export const init = ({ IDL }) => { return []; };